### ISSUE TITLE
Missed icons

### ISSUE THREAD

**Issue by andrewvsk** [khospodarysko/pixelpdf#1]
Where is `icons` folder ?
https://github.com/khospodarysko/pixelpdf/blob/0929e7426970761613eb477d0ad01d3e243c2722/src/main/java/com/kostya/App.java#L46

Add images into `/src/main/resources/icons` folder.

```java
try (InputStream is = App.class.getResourceAsStream("/icons/icon-1.png")) {
   BufferedImage image = ImageIO.read(is);
   PDImageXObject pdImage = LosslessFactory.createFromImage(document, image);
}
```

**Comment by kostia-hospodarysko** [comment]
By design.
